added changelog.md via auto-changelog
react-native-elements/react-native-elements pull request #2640
Opened 2020-10-14 05:50 UTC by Spotts9

https://github.com/react-native-elements/react-native-elements/issues/2626

2020-10-14 06:05 UTC, pranshuchittora reviewed
Can you an npm script for the following so that we can generate this before release or via CI. And document this as well

2020-10-14 20:00 UTC, Spotts9 commented
Followed [doc for Auto-changelog](https://www.npmjs.com/package/auto-changelog) to setup npm script.  Happy to document but not sure where / how.

2020-10-16 06:50 UTC, pranshuchittora requested changes

2020-10-16 06:50 UTC, pranshuchittora commented on package.json
> +    "auto-changelog": "*"
Having a specific version would be great.

2020-10-16 06:50 UTC, pranshuchittora commented on package.json
> +    "version": "auto-changelog -p && git add CHANGELOG.md"
IMO adding CHANGELOG to staging is not required. It may interfere with `husky`

2020-10-16 06:50 UTC, pranshuchittora commented on package.json
> +    "version": "auto-changelog -p && git add CHANGELOG.md"
```suggestion
    "version": "auto-changelog -p"
```

2020-10-16 11:00 UTC, pranshuchittora commented
Pardon, closing this because it's duplicate -> #2637

2020-10-16 11:00 UTC, closed without merging