Add new white, black, and grey colors
react-native-elements/react-native-elements pull request #2674
Opened 2020-11-10 01:08 UTC by phatmann

2020-11-26 00:49 UTC, reinaldosimoes requested changes

2020-11-26 00:49 UTC, reinaldosimoes commented on src/index.d.ts
> +  readonly bkack: string;
```suggestion
  readonly black: string;
```

2020-11-26 01:30 UTC, phatmann commented on src/index.d.ts
> +  readonly bkack: string;
Done

2020-11-26 02:32 UTC, reinaldosimoes approved these changes

2020-11-30 19:15 UTC, pranshuchittora commented
Hi @phatmann any reason for this addition

2020-11-30 19:16 UTC, phatmann commented
They were added to the JS code but the TS declarations were not updated.

2020-12-13 05:27 UTC, merged

2020-12-16 20:44 UTC, flyingcircle commented
@phatmann contact me on the RNE slack for a small token thank you for this PR

2020-12-17 15:43 UTC, phatmann commented
What’s your handle on Slack?

2020-12-17 16:23 UTC, flyingcircle commented
@phatmann same as here.