fix: Header Text Alignment - iOS
react-native-elements/react-native-elements pull request #2706
Opened 2020-12-15 17:04 UTC by pranshuchittora

2020-12-15 18:37 UTC, flyingcircle commented
I tried this out in the example app and it causes the left icon spacing to get off. I'm wondering if we need to somehow include the `SafeAreaView` into the component? Still looking at this myself. Workaround though is to not include the `Header` in a `SafeAreaView`

2020-12-15 19:06 UTC, flyingcircle requested changes
I think we need additional changes here:

I wrote this out in a sample file that I think does what we would want it to do:
```
<>
      <StatusBar barStyle={barStyle} translucent={true} {...statusBarProps} />
      <SafeAreaView style={styles.statusBar(theme)} />
      <SafeAreaView>
      <ViewComponent
      ...
```

```
const styles = {
  statusBar: (theme) => ({
    flex: 0,
    backgroundColor: theme.colors.primary,
  }),
```

2020-12-15 19:07 UTC, flyingcircle requested changes

2020-12-15 19:07 UTC, flyingcircle commented on src/header/Header.js
> +    paddingTop: Platform.select({
This change also needs to be made to the `height` style as well.

2020-12-15 19:29 UTC, flyingcircle commented
I actually found a few additional items that needed changing. I think I'll just open my own PR

2020-12-16 14:16 UTC, pranshuchittora commented
Sure

2020-12-16 14:16 UTC, closed without merging