added onBackdropPress on BottomSheet
react-native-elements/react-native-elements pull request #2749
Opened 2021-01-11 19:25 UTC by superdopey

Added onBackdropPress like on the Overlay component. Users will be able to close the BottomSheet when clicking the backdrop just like how this is done on the Overlay component.

2021-01-15 02:59 UTC, flyingcircle commented
Hey @superdopey thanks for the PR. The prop would also need to be added to the documentation in `website/docs` and also the type needs to be added in the `index.d.ts`. After you've added that, I can do a full code review.

2021-01-25 10:30 UTC, MagicFame commented
Looks good, I think the PR should be merged..

2021-01-29 20:13 UTC, superdopey commented
@flyingcircle I made the changes you suggested.

2021-02-01 12:18 UTC, flyingcircle commented
@superdopey alright I tried it out in the example app but I ran into this:
Current Version:
<img src="https://user-images.githubusercontent.com/5239875/106457495-ea372100-6443-11eb-9d39-6d182513685e.png" width="300">

Branch Code:
<img src="https://user-images.githubusercontent.com/5239875/106457503-eb684e00-6443-11eb-8639-87d7737e382c.png" width="300">

There was also an issue that if the child view was displaying static (not-pressable) elements, the `onBackdropPress` was still being called when they were pressed.

2021-02-01 12:19 UTC, flyingcircle requested changes
Changes requested as mentioned in the above comment.

2021-02-05 09:49 UTC, superdopey commented
> Changes requested as mentioned in the above comment.

@flyingcircle The changes are applied. Btw I am still new to doing pull-request like this, when I push changes do I need to comment here or do you see the changes regardless of the comment?

2021-03-09 08:04 UTC, superdopey commented
> > Changes requested as mentioned in the above comment.
> 
> @flyingcircle The changes are applied. Btw I am still new to doing pull-request like this, when I push changes do I need to comment here or do you see the changes regardless of the comment?

@flyingcircle Is there some else you need before we can continue this PR?

2021-03-09 17:21 UTC, flyingcircle commented
@superdopey I made some typescript changes. Hopefully it doesn't interfere with your changes here, but can you pull and merge the current `next` branch into your PR to resolve the "conflicting" files and then I'll test it out again.

2021-04-11 00:10 UTC, closed without merging