changed Button to a functional component
react-native-elements/react-native-elements pull request #2820
Opened 2021-03-10 17:05 UTC by deevo-sage

converted the button class component to a functional component. I decided to convert all the class components to functional components after reading the migration to hooks in the list of ideas mentioned in [ideas.md](https://github.com/react-native-elements/org/blob/master/GSoC/ideas.md). It passed all the tests and I also tested it in a basic react-native app. looking forward to doing the same with other class components.

2021-03-11 16:12 UTC, flyingcircle requested changes

2021-03-11 16:12 UTC, flyingcircle commented on src/buttons/Button.tsx
> +  }, [props]);
You have `useMemo` here, but it triggers on all changes to props? I don't think this is a better solution.

2021-03-11 22:01 UTC, deevo-sage commented
@flyingcircle I did the requested changes

2021-03-12 16:16 UTC, flyingcircle commented
Lots of people submitted a PR for this, taking #2834 Thanks for your contribution.

2021-03-12 16:16 UTC, closed without merging