add new social icons:facebook-messenger and whatsapp
react-native-elements/react-native-elements pull request #2826
Opened 2021-03-11 16:37 UTC by abhishekkumar08

Two new social icons added to SocialIcons component: facebook-messenger and WhatsApp.

2021-03-11 16:38 UTC, abhishekkumar08 commented
I haven't tested the changes can you tell me @flyingcircle, how should I test these locally?

2021-03-11 17:03 UTC, flyingcircle commented
I would test them using the `react-native-elements-app`. It's one of the other repos in our github.

2021-03-11 17:10 UTC, abhishekkumar08 commented
@flyingcircle can you please tell me the steps how to do that. Thanks for the reply

2021-03-12 15:19 UTC, flyingcircle commented
@abhishekkumar08 there's no 'facebook-messenger' icon in font-awesome (you can view the icons available here: https://oblador.github.io/react-native-vector-icons/) You'd have to change the icon type to something like 'material-community' in order to see it.

2021-03-14 04:06 UTC, flyingcircle requested changes
Documentation needs updated

2021-03-14 09:13 UTC, abhishekkumar08 commented
Upon checking the code ```#available-icon-sets``` links doesn't work correctly, updated in the commit  ```45732f2```, I haven't added all the types as I don't have confirmation for all the types. Can you please tell me the other types which I have not added? @flyingcircle

2021-03-14 17:15 UTC, flyingcircle requested changes
I think you got a little confused, just add the new items to the social media type list and remove the other items that you added. Also you shouldn't change the `versioned_docs` but the `docs` files.

2021-03-14 17:15 UTC, flyingcircle commented on website/versioned_docs/version-3.3.1/props/icon.md
> +### `available-icon-sets`
I don't know why you added this.

2021-03-14 17:15 UTC, flyingcircle commented on website/versioned_docs/version-3.3.1/props/social_icons.md
> +| social media type (angellist, codepen, envelope, etsy, facebook, facebook-messenger, flickr, foursquare, github-alt, github, gitlab, instagram, linkedin, medium, pinterest, quora, reddit-alien, sou
The only thing I meant was that the 2 items should be added to this list. But not in the `versioned_docs` folder, but in the `docs` folder.

2021-03-14 17:15 UTC, flyingcircle commented on website/versioned_docs/version-3.3.1/props/social_icons.md
> +### `available-icon-sets`
this should not be here also.

2021-03-14 17:55 UTC, abhishekkumar08 commented
> 
> 
> I think you got a little confused, just add the new items to the social media type list and remove the other items that you added. Also you shouldn't change the `versioned_docs` but the `docs` files.

Sorry for that, I went in flow and checked all the links. Edited the code as requested please have a look now. Thanks for the review.

2021-03-14 18:58 UTC, merged