Theme can now be changed on changing the state of component
react-native-elements/react-native-elements pull request #2833
Opened 2021-03-12 05:00 UTC by hetanthakkar1

**What kind of change does this PR introduce?**

Added ability to change the theme for a component tree via state change
Fixed issue #2754

2021-03-12 05:02 UTC, hetanthakkar1 commented
Sorry for the multiple commits that resulted because of multiple commits I did for testing my changes

2021-03-12 05:06 UTC, hetanthakkar1 commented
Demo Code which can is now supported:

![image](https://user-images.githubusercontent.com/38756320/110894848-a676e780-831e-11eb-8b6d-b4e929656a9c.png)



import { ThemeProvider, Button } from "react-native-elements";
import React, { useState } from "react";
const theme1 = {
  Button: {
    titleStyle: {
      color: "white",
    },
  },
};
const theme2 = {
  Button: {
    titleStyle: {
      color: "yellow",
    },
  },
};
export default function App() {
  const [theme, setTheme] = useState(theme1);
  return (
    <ThemeProvider theme={theme}>
      <Button
        title="My Button"
        onPress={() => {
          if (theme == theme1) {
            setTheme(theme2);
          } else {
            setTheme(theme1);
          }
        }}
      />
      <Button
        title="My 2nd Button"
        onPress={() => {
          if (theme == theme1) {
            setTheme(theme2);
          } else {
            setTheme(theme1);
          }
        }}
      />
    </ThemeProvider>
  );
}

2021-03-12 05:07 UTC, hetanthakkar1 commented
@flyingcircle  You can use my above code to test my changes

2021-03-12 17:23 UTC, hetanthakkar1 commented
@flyingcircle  Could you please review!?

2021-03-14 05:12 UTC, flyingcircle requested changes

2021-03-14 05:12 UTC, flyingcircle commented on src/config/ThemeProvider.tsx
> +      update: true,
I don't understand the use of update and setting it true here. Are we saying that if you run `updateTheme` then changing the `theme` prop will stop working? How about we just go without the update variable and just update the `theme` as it is passed in.

2021-03-14 15:46 UTC, hetanthakkar1 commented
@flyingcircle  So we are updating theme at 2 places in my code .One at the updateTheme method and other at getDerivedStateFromProps method so we dont want to execute both of them to do the same.So if updateTheme function will update theme it will set the update to true and so the updation in getDerivedStateFromProps wont take place.Removing that update state will also fail 1 test case

2021-03-14 22:46 UTC, flyingcircle commented
@hetanthakkar1 What I'm asking is if a user updated the theme using `updateTheme`and then updates it later by changing the `theme` prop, the theme wouldn't update the second time right? I don't see where in this code that `update` gets switched back to `false`.

2021-03-15 02:35 UTC, hetanthakkar1 commented
@flyingcircle  I got your point and I have made the necessary changes. Can you please review

2021-03-15 02:41 UTC, hetanthakkar1 commented
@flyingcircle Okay i got your point. I am thinking on it. Please ignore the last commit . I pushed it by mistake that it will fix but realized later that it isn't correct and didnt wat to delete commit by force pushing

2021-03-21 00:35 UTC, closed without merging