Added New Component: TabView
react-native-elements/react-native-elements pull request #2919
Opened 2021-03-26 08:09 UTC by arpitBhalla

**What kind of change does this PR introduce?**

**Did you add tests for your changes?**

**If relevant, did you update the documentation?**

**Summary**
https://material.io/components/tabs

**Does this PR introduce a breaking change?**

**Other information**

2021-03-26 19:48 UTC, flyingcircle commented
How is this different from `ButtonGroup`?

2021-03-26 23:30 UTC, arpitBhalla commented
![FWojY](https://user-images.githubusercontent.com/55053424/112702419-646ea980-8eb9-11eb-94ee-76da70117168.png)
![AFgz0](https://user-images.githubusercontent.com/55053424/112702428-69cbf400-8eb9-11eb-895a-b763cbfc732e.png)

2021-03-27 05:35 UTC, arpitBhalla commented
@pranshuchittora Should I continue on this?

2021-03-28 16:32 UTC, arpitBhalla commented
@flyingcircle Should I continue on this?

2021-03-28 18:16 UTC, flyingcircle commented
I think as an alternative styling of `ButtonGroup` this could be a nice simple addition. Sure.

2021-03-30 18:45 UTC, arpitBhalla commented
@flyingcircle  Please Review the props and code

2021-04-10 19:29 UTC, arpitBhalla commented
@flyingcircle Please Review

2021-04-11 21:02 UTC, flyingcircle requested changes

2021-04-11 21:02 UTC, flyingcircle commented on src/index.ts
> +export { default as Tab } from './tab/tab';
Why not follow the pattern of the rest of the file? Please use the same pattern as every other component.

2021-04-12 04:21 UTC, merged