jsx error
react-native-elements/react-native-elements pull request #3038
Opened 2021-05-16 13:38 UTC by zairigimad

**What kind of change does this PR introduce?**

**Did you add tests for your changes?**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

2021-05-16 13:42 UTC, arpitBhalla commented
Hey @zairigimad, make changes in this file, https://github.com/react-native-elements/react-native-elements/blob/next/website/docs/switch.md

2021-05-16 13:43 UTC, arpitBhalla requested changes

2021-05-16 13:43 UTC, arpitBhalla commented on website/versioned_docs/version-3.4.1/switch.md
> +<Switch value={false} color="orange"/>
Make change in, https://github.com/react-native-elements/react-native-elements/blob/next/website/docs/switch.md

2021-05-20 09:15 UTC, arpitBhalla commented on website/versioned_docs/version-3.4.1/switch.md
> +<Switch value={false} color="orange"/>
Linked PR #3041

2021-05-23 18:26 UTC, flyingcircle commented
These docs won't last too long as they'll be replaced with the correction in the next version. We'll just wait til then

2021-05-23 18:26 UTC, closed without merging