bottomsheet- added onBackdropPress for close bottomsheet
react-native-elements/react-native-elements pull request #3074
Opened 2021-06-09 16:25 UTC by kedar09

**What kind of change does this PR introduce?**

I have added the onBackdropPress function for close bottomsheet.

**Did you add tests for your changes?**
Yes
**If relevant, did you update the documentation?**

**Summary**

I have used package 

**Does this PR introduce a breaking change?**
No

**Other information**

2021-06-20 12:13 UTC, khushal87 commented
Please resolve merge conflicts.

2021-06-20 12:14 UTC, khushal87 reviewed
Please resolve merge conflicts.

2021-06-21 13:07 UTC, arpitBhalla commented on src/bottomSheet/BottomSheet.tsx
> +
Could you use `Pressable`?

2021-07-05 16:00 UTC, arpitBhalla approved these changes

2021-07-05 16:01 UTC, arpitBhalla commented
@kedar09 Can you resolve conflict

2021-07-08 17:41 UTC, arpitBhalla approved these changes

2021-07-08 17:44 UTC, kedar09 commented
> @kedar09 Can you resolve conflict
I have updated the code with the latest code in the next branch and push that changes

2021-08-03 19:17 UTC, jorgegvallejo commented
Hope this gets added to the next release :pray:

2021-08-09 14:57 UTC, flyingcircle commented
I tried this out in the demo expo app. Did not work.

2021-08-09 14:58 UTC, flyingcircle requested changes
Tested this in the demo app. Did not work.

2021-08-11 21:09 UTC, kedar09 commented
> pointerEvents={'none'}

@arpitBhalla i have used 
style={[StyleSheet.absoluteFill, styles.backdrop, backdropStyle]}
and pointerEvents="box-none"
its worked
```

return (<Modal onRequestClose={onBackdropPress} animationType="slide" transparent={true} visible={isVisible} {...modalProps}>
    <Pressable onPress={onBackdropPress}   
    style={[StyleSheet.absoluteFill, styles.backdrop, backdropStyle]}
     testID="RNE__Overlay__backdrop" />
    
      <SafeAreaView style={StyleSheet.flatten([
        styles.safeAreaView,
        containerStyle && containerStyle,
    ])} {...props} pointerEvents="box-none">
        <View>
          <ScrollView {...scrollViewProps}>{children}</ScrollView>
        </View>
      </SafeAreaView>
    </Modal>);
```

2021-08-12 03:41 UTC, arpitBhalla commented
> @arpitBhalla i have used
style={[StyleSheet.absoluteFill, styles.backdrop, backdropStyle]}
and pointerEvents="box-none"
its worked

Pls Update the PR, so maintainers can review.

2022-02-03 06:14 UTC, ridie001 approved these changes

2022-02-05 14:21 UTC, arpitBhalla approved these changes

2022-02-05 14:25 UTC, merged

2022-02-05 14:26 UTC, arpitBhalla commented
Thank you for your contribution 🎉