Scrolling was added to tabs. Implemetation:ScrollView added to map al…
react-native-elements/react-native-elements pull request #3336
Opened 2022-02-04 12:48 UTC by entrymaster

…ong with scrollHandler( ) function which syncs the scrollview with active tab.

**What kind of change does this PR introduce?**

**Did you add tests for your changes?**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

2022-02-04 12:56 UTC, entrymaster commented
Scrolling Tabs added with syncing

2022-02-04 14:02 UTC, entrymaster reviewed
I have removed some unnecessary code.

2022-02-12 09:19 UTC, arpitBhalla requested changes

2022-02-12 09:19 UTC, arpitBhalla commented on packages/base/src/Tab/Tab.tsx
> +  tabScrolling?: boolean;
Use `scrollable` instead

2022-02-12 09:19 UTC, arpitBhalla commented on packages/base/src/Tab/Tab.tsx
> +  const [scrollViewRef, setScrollViewRef] = React.useState(null);
Use `useRef` instead of state

2022-02-12 13:09 UTC, entrymaster reviewed
OKay

2022-02-12 14:02 UTC, merged