fix:swipe animation disabling option in tabview (#3232)
react-native-elements/react-native-elements pull request #3372
Opened 2022-02-25 10:12 UTC by Sinharitik589

**What kind of change does this PR introduce?**

feature

**Did you add tests for your changes?**
NO

**If relevant, did you update the documentation?**
NO

**Summary**

#3232 

**Does this PR introduce a breaking change?**

**Other information**

2022-02-25 10:22 UTC, arpitBhalla requested changes

2022-02-25 10:22 UTC, arpitBhalla commented on packages/base/src/TabView/TabView.tsx
> +  swipeEnabled?: Boolean;
`swipeEnabled`->`disableSwipe`

2022-02-25 10:22 UTC, arpitBhalla commented on packages/base/src/TabView/TabView.tsx
> +              width: window.width * length,
Don't repeat same code

2022-03-05 09:34 UTC, arpitBhalla requested changes

2022-03-05 09:34 UTC, arpitBhalla commented on packages/base/src/TabView/TabView.tsx
> +    }
I don't think this would make any change, did you tried on example app?

2022-03-05 09:54 UTC, arpitBhalla commented
Thank you for your contribution 🎉

2022-03-05 09:57 UTC, merged

2022-03-05 16:08 UTC, monk-lee commented
Can you let me use it
`react-native-elements/react-native-elements#base`
`react-native-elements/react-native-elements#themed`, too?

2022-03-05 16:23 UTC, arpitBhalla commented
yeah, just delete lock file and reinstall